
spring:
  application:
    name: ms-gateway
  profile:
    default: eureka-on
server:
  port: 4040

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/