
spring:
  application:
    name: ms-gateway
  profile:
    default: default
server:
  port: 4040

eureka:
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/